# Playbook to backup home directory files
---
  - hosts: dev
    gather_facts: no
    tasks:
      - name: Retrieve the list of home directories
        command: ls /home
        register: home_dirs
      - debug:
          msg: "{{ home_dirs }}"
      - name: add home dirs to the backup
        file:
         path: /tmp/home_bk/{{ item }}
         src: /home/{{ item }}
         state: directory
        loop: "{{ home_dirs.stdout_lines }}"
   
   
   

