---
  - hosts:
    remote_users: apache
    become: true
    tasks:
        - name: Install apache
          yum: name=httpd state=present
          ignore_errors: true
        - name: Install PHP
          yum: name=php5 state=present
          ignore_errors: true
        - name: Apache service restart
          service: name=httpd state=restarted
          ignore_errors: true